theme: jekyll-theme-slate

title: Will Sutton
url: "https://wjsutton.github.io"
baseurl: ""

# List of links in the navigation bar
navbar-links:
  Home: "_home/homepage.md"
  Tableau Tips & Tricks: "_tableau_tips_and_tricks/Tableau-Tips-Tricks-0-Home.md"
  Project Walkthroughs: "_project_walkthroughs/walkthroughs.md"
  About Me: "_about_me/about.md"


navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040" 
  
author:
  name: Will Sutton