title: Will Sutton
url: "https://wjsutton.github.io"
baseurl: ""

repository: wjsutton/wjsutton.github.io
github: [metadata]
  
author:
  name: Will Sutton
  
kramdown:  
  parse_block_html: true
  
theme:  jekyll-theme-slate

google_analytics: UA-134645025-1

paginate: 5